# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

hostname        = "ronex-indigo"
memory          = ENV['VAGRANT_MEMORY']  || '2048'
cores           = ENV['VAGRANT_CORES']   || '2'
vram            = ENV['VAGRANT_VRAM']    || '128'
ansible_verbose = ENV['ANSIBLE_VERBOSE'] || "vv"

Vagrant.configure(VAGRANTFILE_API_VERSION)  do |config|
  config.vm.box      = "shadowrobot/ros-indigo-desktop-trusty64"
  config.vm.hostname = hostname

  # Public network for ssh access, shares etc
  # XXX Breaks network access out of the machine as connection manager seems to
  # use this instead of the natted connection.
  #config.vm.network :public_network, :public_network => 'eth1', ip: "123.123.123.123"

  # Adding private network interface for local access to ssh, shares etc
  config.vm.network :private_network, type: :dhcp, :adapter => 3

  # Set the vagrant name so we can match it in ansible
  config.vm.define hostname do |host|
  end

  config.ssh.forward_agent = true

  # VirtualBox
  config.vm.provider :virtualbox do |vb|
      vb.gui = true
      # Use VBoxManage to customize the VM.
      vb.customize ["modifyvm", :id, "--memory", memory.to_i]
      vb.customize ["modifyvm", :id, "--cpus", cores.to_i]
      vb.customize ["modifyvm", :id, "--vram", vram.to_i]
  end

  # Provisioning with Ansible
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../../../ansible/vagrant_site.yml"
      if ansible_verbose != ""
          ansible.verbose  = ansible_verbose
      end
  end

end
