# Copyright 2023 Shadow Robot Company Ltd.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

version: 0.2
env:
  variables:
     image_name: public.ecr.aws/shadowrobot/dexterous-hand
     image_tag: noetic-v1.0.2
     image_previous_tag: ""
     image_repository: dexterous-hand
     release_branch: master
  parameter-store:
     GITHUB_LOGIN : GITHUB_LOGIN
     GITHUB_PASSWORD : GITHUB_PASSWORD
  exported-variables:
     - image_name
     - image_tag
     - image_previous_tag
     - image_repository
     - release_branch
phases:
  pre_build:
    commands:
      - apt-get install --only-upgrade bash
      - git checkout $release_branch
      - echo AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI >> AWS_CRED
      - echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> AWS_CRED
      - cd $(find . -name bin)
      - cd $(find . -name gather_changelog)
  build:
    commands:
      - ./gather_changelog.sh "$image_name" "$image_tag" "$image_repository" "$image_previous_tag"