# Install Mujoco Simulator

- name: Download Mujoco software in home
  shell: bash -c "wget "https://www.roboti.us/download/mjpro150_linux.zip" -P /home/{{ros_user}}"
  become: yes

- name: Unzip Mujoco software
  shell: bash -c "unzip /home/{{ros_user}}/mjpro150_linux.zip -d /home/{{ros_user}}"
  become: yes
  
- name: Fix mujoco folder ownership
  become: yes
  file:
    path: "/home/{{ros_user}}/mjpro150"
    owner: "{{ros_user}}"
    group: "{{ros_user}}"
    recurse: yes

- name: Install libglfw3-dev
  become: yes
  apt:
    name: libglfw3-dev

- name: Install libglew
  become: yes
  apt:
    name: libglew-dev
