# Copyright 2023 Shadow Robot Company Ltd.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

---
- name: Update package lists
  apt:
    update_cache: yes
  become: yes
  changed_when: false

# - name: Ensure botocore and boto3 modules are installed
#   pip:
#     name: [ "boto3", "botocore"]
#     extra_args: "--user"

# - name: Downloading ur_client_library
#   amazon.aws.s3_object:
#     aws_access_key: "{{ lookup('env','aws_key') }}"
#     aws_secret_key: "{{ lookup('env','aws_secret') }}"
#     bucket: "{{ bucket_name }}"
#     object: "{{ folder_name }}/{{ ur_client_filename }}"
#     dest: "/tmp/{{ ur_client_filename }}"
#     mode: get

# - name: Install ur_client_library.deb package
#   apt:
#     deb: "/tmp/{{ ur_client_filename }}"
#     state: present

# - name: Removing steamvr.tar.gz file
#   file:
#     path: "/tmp/{{ ur_client_filename }}"
#     state: absent

- name: Copy ros-noetic-ur-client-library .deb file
  copy:
    src: files/ros-noetic-ur-client-library_1.3.1-1focal.20221201.233814_amd64.deb
    dest: /tmp/ros-noetic-ur-client-library.deb

- name: Install ros-noetic-ur-client-library from .deb file
  apt:
    deb: /tmp/ros-noetic-ur-client-library.deb
    state: present
  become: yes
  become_method: sudo
  become_user: root

- name: Remove file
  file:
    path: /tmp/ros-noetic-ur-client-library.deb
    state: absent
