# Copyright 2022 Shadow Robot Company Ltd.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

version: 0.2

env:
  shell: bash
  variables:
    branch: default
    image: build-tools
    tag: bionic-melodic
    dockerfile_folder: docker/ros/melodic/
  exported-variables:
    - branch
    - image
    - tag
    - dockerfile_folder
phases:
  install:
    runtime-versions:
      docker: 19
  build:
    commands:
      - |
        if [[ $branch != "default" ]]; then
          toolset_branch=$branch
        elif [[ $CODEBUILD_SOURCE_VERSION == "pr/"* ]]; then
          pr_number=${CODEBUILD_SOURCE_VERSION#pr/}
          toolset_branch=$(curl -s "https://api.github.com/repos/shadow-robot/sr-build-tools/pulls/$pr_number" | jq -r '.head.ref')
        elif [[ $CODEBUILD_SOURCE_VERSION =~ ^[0-9a-f]{40}$ ]]; then
          toolset_branch=$(git ls-remote --symref origin | grep -m1 $CODEBUILD_SOURCE_VERSION | awk -F '/' '{print $NF}')
        else
          toolset_branch=$CODEBUILD_SOURCE_VERSION
        fi
      - awscli_v1_executable=$(which aws)
      - rm $awscli_v1_executable
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - git checkout $toolset_branch
      - cd $dockerfile_folder
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/shadowrobot
      - docker build --build-arg toolset_branch=$toolset_branch -t $image .
      - docker tag $image:latest public.ecr.aws/shadowrobot/$image:$tag
      - docker push public.ecr.aws/shadowrobot/$image:$tag
      - comm -13 <(aws ecr-public describe-image-tags --repository-name $image --region us-east-1 --output text | awk '{print $3}' | tr " " "\n" | sort -u) <(aws ecr-public describe-images --repository-name $image --region us-east-1 --output text | awk '{print $2}' | tr " " "\n" | sort -u) >> ids_to_delete.txt
      - ids_to_delete=$(sed 's/^/imageDigest=/' ids_to_delete.txt)
      - if [[ -s ids_to_delete.txt ]]; then aws ecr-public batch-delete-image --repository-name $image --region us-east-1 --image-ids $ids_to_delete --output text; fi
