# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

hostname        = "ronex"
memory          = ENV['VAGRANT_MEMORY']  || '1024'
cores           = ENV['VAGRANT_CORES']   || '2'
vram            = ENV['VAGRANT_VRAM']    || '64'
ansible_verbose = ENV['ANSIBLE_VERBOSE'] || ""

Vagrant.configure(VAGRANTFILE_API_VERSION)  do |config|
  config.vm.box      = "ros-hydro-desktop-precise64"
  config.vm.box_url  = "http://files.shadowrobot.com/vagrant/ros-hydro-desktop-precise64.box"
  config.vm.hostname = hostname
  config.vm.network :public_network, :public_network => 'eth1', ip: "123.123.123.123"

  # Set the vagrant name so we can match it in ansible
  config.vm.define hostname do |host|
  end

  config.ssh.forward_agent = true

  # VirtualBox
  config.vm.provider :virtualbox do |vb|
      vb.gui = true
      # Use VBoxManage to customize the VM.
      vb.customize ["modifyvm", :id, "--memory", memory.to_i]
      vb.customize ["modifyvm", :id, "--cpus", cores.to_i]
      vb.customize ["modifyvm", :id, "--vram", vram.to_i]
  end

  # Provisioning with Ansible
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../../ansible/vagrant_site.yml"
      if ansible_verbose != ""
          ansible.verbose  = ansible_verbose
      end
  end

end
