# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

hostname = "ros-hydro-desktop-precise64"
memory   = ENV['VAGRANT_MEMORY'] || '1024'
cores    = ENV['VAGRANT_CORES']  || '2'
vram     = ENV['VAGRANT_VRAM']   || '64'

nodes = [
    { :name => 'ros-hydro-desktop-precise64', :box => 'precise64' },
    { :name => 'ros-indigo-desktop-trusty64', :box => 'nimbus/trusty' },
]

Vagrant.configure(VAGRANTFILE_API_VERSION)  do |config|
  # Create a machine for each of the nodes.
  nodes.each do |node|
      config.vm.define node[:name] do |node_config|
          node_config.vm.box      = node[:box]
          node_config.vm.hostname = node[:name]
      end
  end

  config.ssh.forward_agent = true

  # VirtualBox
  config.vm.provider :virtualbox do |vb|
      vb.gui = true
      # Use VBoxManage to customize the VM.
      vb.customize ["modifyvm", :id, "--memory", memory.to_i]
      vb.customize ["modifyvm", :id, "--cpus", cores.to_i]
      vb.customize ["modifyvm", :id, "--vram", vram.to_i]
  end

  # Provisioning with Ansible
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../../ansible/vagrant_site.yml"
  end

end
