# Copyright 2022 Shadow Robot Company Ltd.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

---
# Playbook for codecov

- name: check if codecov_secure variable was set
  fail: msg="Variable codecov_secure was not set"
  when: (codecov_secure is not defined) or (codecov_secure == "")

- name: check if code_coverage_results_dir variable was set by build server
  fail: msg="Variable code_coverage_results_dir was not set by CI server"
  when: code_coverage_results_dir is not defined

- name: Send data to codecov
  shell: bash -c "cd {{repo_sources_path}} && bash <(curl -s https://codecov.io/bash) -f {{code_coverage_results_dir}}/coverage.cpp.xml -f {{code_coverage_results_dir}}/coverage.python.xml"
  environment:
        CODECOV_TOKEN: "{{codecov_secure}}"
