# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

MEMORY = ENV['VAGRANT_MEMORY'] || '1024'
CORES = ENV['VAGRANT_CORES'] || '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box      = "ros-hydro-desktop-precise64"
  config.vm.box_url  = "http://TODO.example.com/rosbase-hydro-precise64.box"
  config.vm.hostname = "hand-hydro-precise64.box.local"

  config.ssh.forward_agent = true

  # VirtualBox
  config.vm.provider :virtualbox do |vb|
      vb.gui = true
      # Use VBoxManage to customize the VM.
      vb.customize ["modifyvm", :id, "--memory", MEMORY.to_i]
      vb.customize ["modifyvm", :id, "--cpus", CORES.to_i]
  end

  # Provisioning with Ansible
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../../ansible/hand.yml"
  end

end
